updated readme
Hochfrequenz/python_template_repository pull request #37
Opened 2022-11-22 15:46 UTC by SimonKapanke

2022-11-22 16:03 UTC, hf-aschloegl commented
Kannst du die env Zeile aus den settings auch noch ergänzen?

2022-11-23 15:22 UTC, hf-aschloegl requested changes
Kannst du die env Zeile aus den settings auch noch ergänzen?

2022-11-24 08:33 UTC, SimonKapanke commented
> 

Die Zeile mit env. in den Settings ist nicht notwendig, damit es funktioniert.

2022-11-24 08:34 UTC, hf-aschloegl approved these changes

2022-11-24 08:36 UTC, merged